; ============================================================================
;  VoxKey.iss — CLASSIC Windows installer (Inno Setup)
;
;  Produces the traditional Setup.exe wizard: welcome, licence, install
;  location, component choices, Start-Menu group, a real extraction progress
;  bar, and a full uninstaller. Bundles the PyInstaller onedir build, so the
;  end user needs NOTHING installed (Python + Qt + model runtime all included).
;
;  Build:
;    1) pyinstaller VoxKey.spec           -> dist\VoxKey\ (app + runtime)
;    2) iscc installer\VoxKey.iss         -> dist\VoxKey-Setup.exe
;  (build_installer.bat does both automatically and fetches Inno if missing.)
; ============================================================================

#define AppName        "VoxKey"
#define AppVersion     "1.0.0"
#define AppPublisher   "VoxKey"
#define AppExeName     "VoxKey.exe"
#define AppId          "{{9F2C7E14-4B8A-4E2D-9C3F-VOXKEY000001}"

[Setup]
AppId={#AppId}
AppName={#AppName}
AppVersion={#AppVersion}
AppPublisher={#AppPublisher}
AppVerName={#AppName} {#AppVersion}
DefaultDirName={autopf}\{#AppName}
DefaultGroupName={#AppName}
UninstallDisplayIcon={app}\{#AppExeName}
UninstallDisplayName={#AppName}
OutputDir=..\dist
OutputBaseFilename=VoxKey-Setup
Compression=lzma2/max
SolidCompression=yes
WizardStyle=modern
PrivilegesRequiredOverridesAllowed=dialog
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
DisableWelcomePage=no
; Branding graphics (generated by the build; safe if present)
WizardImageFile=wizard_large.bmp
WizardSmallImageFile=wizard_small.bmp
SetupIconFile=voxkey.ico
LicenseFile=LICENSE.txt

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional shortcuts:"
Name: "startupicon"; Description: "Start {#AppName} automatically when I sign in to Windows"; GroupDescription: "Startup:"

[Files]
; The entire PyInstaller onedir output (app + bundled Python/Qt runtime)
Source: "..\dist\VoxKey\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
; The speech worker lives in its own subfolder with its own DLLs (dist\VoxKey\whisper),
; which the recursesubdirs flag above already carries across. Verify it arrived:
Source: "..\dist\VoxKey\whisper\VoxKey-Whisper.exe"; DestDir: "{app}\whisper"; Flags: ignoreversion

[Icons]
Name: "{group}\{#AppName}"; Filename: "{app}\{#AppExeName}"
Name: "{group}\Uninstall {#AppName}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: desktopicon
Name: "{userstartup}\{#AppName}"; Filename: "{app}\{#AppExeName}"; Tasks: startupicon

[Run]
Filename: "{app}\{#AppExeName}"; Description: "Launch {#AppName} now"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
; Remove app data written at runtime (transcripts, config, model cache stays in user profile)
Type: filesandordirs; Name: "{userappdata}\VoxKey"

[Code]
{ Optional: a friendly custom page after install explaining the hotkey. }
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    { placeholder for future post-install actions (e.g. model pre-download) }
  end;
end;
